baseURL = "https://rainmatter.org"
languageCode = "en-us"
title = "Rainmatter Foundation"
paginate = 10
googleAnalytics = ""

[params]
subtitle = "Non-profit working on environment, climate change, green livelihood projects in India."

[taxonomies]
   tag = "tags"
   author = "authors"

[menu]
   [[menu.header]]
      identifier = "about"
      name = "About"
      url = "/about"
      weight = 1

   [[menu.header]]
      identifier = "partners"
      name = "Partners"
      url = "/Partners"
      weight = 2

   [[menu.header]]
      identifier = "thesis"
      name = "Thesis"
      url = "/thesis"
      weight = 3

   [[menu.header]]
      identifier = "resources"
      name = "Resources"
      url = "/resources"
      weight = 4

   [[menu.header]]
      identifier = "blog"
      name = "Blog"
      url = "https://blog.rainmatter.org"
      weight = 5

   [[menu.header]]
      identifier = ""
      name = "Forum"
      url = "https://grove.rainmatter.org"
      weight = 6

[markup.goldmark.renderer]
   unsafe= true
